### PR TITLE
Make sure all files end in a newline

### PR DESCRIPTION
**Pull request by khellang**
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

Just annoyed me a bit 😛

### CODE REVIEW

**Comment by kevinchalet** [comment]
Ready to merge?

**Comment by khellang** [comment]
Go for it! 😄

**Comment by kevinchalet** [comment]
Alright, thanks for this PR. I'll merge it as soon as Travis finishes building it (looks like it's having a hard time processing logs :sweat_smile:)

**Comment by kevinchalet** [comment]
FYI there's a little conflict caused by our migration to the latest KoreBuild scripts.

While we're at it, is there's a chance you could submit the same PR against the release branch? (it has `*Helper` files that won't be covered by this one once we merged it back into `release`).

Thanks.

**Comment by kevinchalet** [comment]
Merged, thanks for your contribution! :+1:

**Pull request merged**
