### PR TITLE
Dropbox fixes

### PR DESCRIPTION
**Pull request by scrappydog**
Fixes for new paths to Dropbox v2 api endpoints.
Reincorporated additional claims from 1.0.0 version.

### CODE REVIEW

**Comment by scrappydog** [comment]
Reason for closing this without merging?  I'm happy to make changes or fixes if needed?

Thanks

**Comment by kevinchalet** [comment]
Sorry, that was not intentional: you made a little mistake by targeting the `rel/2.0.0-rc2 branch` and GitHub automatically closed your PR when I deleted it.

**Comment by kevinchalet** [comment]
> I'm happy to make changes or fixes if needed?

Note: you made indent changes that are not wanted (we use spaces and not tabs) and it looks like you added back the `Helper` class, which is not used in the 2.0.0 version. Any chance you could revert these changes?

**Comment by kevinchalet** [comment]
Don't worry about the style changes, I'll cherry-pick your commit and make the changes locally.

**Comment by kevinchalet** [comment]
This PR was merged into the `release` branch (1.0 providers) and ported to the `dev` branch (2.0): https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/b54f7b37c7386f88210e5ab7794f4eac13290038

Thanks for your contribution!

**Pull request closed without merging**
