### PR TITLE
Add HealthGraph provider.

### LINKED ISSUE #9: Add HealthGraph provider

### PR DESCRIPTION
**Pull request by Res42**
Closes #9.

### CODE REVIEW

**Comment by PinpointTownes** [comment]
Woot, thanks for this new contribution! :clap: 

One question: what's the relationship between HealthGraph and runkeeper (used in the endpoint URLs)?

**Comment by Res42** [comment]
Runkeeper owns HealthGraph.

**Comment by PinpointTownes** [comment]
So `HealthGraph` is like a product name actually?

Is it worth using the `Runkeeper` name to match the conventions used by the other providers, that only use the company name?

**Comment by Res42** [comment]
If I understand it right, `Runkeeper` is the company, and they own:
* the `Runkeeper` application (which uses `HealthGraph`) 
* `HealthGrapth`, which is the underlying API.

In their documentation they call the API we connect to `HealthGraph` so I called the provider that.

As for the general naming convention, I thought the convention was to call them by the product name.
What would we call the `Battle.Net` provider? `BattleNet` or `BlizzardEntertainment` or `ActivisionBlizzard`?
Instagram is owned by Facebook, should it be called `Facebook2` (`Facebook` is used for `Facebook`)?

**Comment by PinpointTownes** [comment]
As you figured out, I meant the product name (which is often the same as the company name), by opposition to the API name :smile: 

(that's why the Facebook provider is named "Facebook" and not "SocialGraph" and the Google provider, "Google" and not "GooglePlus")

But if you think the API name (`HealthGraph`) is more appropriate, I'm fine :+1:

**Comment by Res42** [comment]
I do not use this service (or knew about it before writing this) so I don't really care about what it is called here. I can easily change it if you want.
I only used the `HealthGraph` name because in  issue #9 and in the previous project RockstarLabs/OwinOAuthProviders@188bbe43aeed4158d7b2701d75ae055a0b86bc1d it was called `HealthGraph`.

**Comment by PinpointTownes** [comment]
@jerriep any opinion? :smile:

**Comment by jerriep** [comment]
I'd say keep it HealthGraph, because that is the name of the product.

**Comment by PinpointTownes** [comment]
Merged, thanks for your contribution! https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/060ef4ae403606292b71dba1b12f046c4b55f320

**Pull request closed without merging**
