### PR TITLE
Update the BitBucket/GitHub/Weibo providers to throw an exception when failing to retrieve user's email address

### PR DESCRIPTION
**Pull request by kevinchalet**
Fixes https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/313.

/cc @martincostello

### CODE REVIEW

**Review by martincostello — APPROVED** [review]

**Comment by kevinchalet** [comment]
Thanks for the review! FYI, I ported the changes to dev as part of this merge commit: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/42344320fa905c5052398f4fed058bba4f604c6a

**Comment by martincostello** [comment]
Cool - I'll port the other changes (two new providers, plus Source Link) over to `rel/2.1.0` at lunctime.

**Comment by kevinchalet** [comment]
> plus Source Link

We should probably do that in the OpenID repo too, for consistency. Lemme know if you want to take care of it 😎

**Comment by martincostello** [comment]
Sure, I'll do that later on today too 😃

**Comment by martincostello** [comment]
I've cherry-picked the various commits over to `rel/2.1.0` now. I wasn't sure what the best git-fu to sync/merge the branches and not pull over the version change from `dev` was.

**Comment by martincostello** [comment]
SourceLink in https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/pull/60.

**Comment by kevinchalet** [comment]
> I wasn't sure what the best git-fu to sync/merge the branches and not pull over the version change from dev was.

Cherry-picking is perfect 😄

**Pull request merged**
