### PR TITLE
Adding support for "Sign In with LinkedIn using OpenID Connect" aka V2 API

### PR DESCRIPTION
**Pull request by solrevdev**
See Issue #781 

Draft for now. Will work on this week hopefully. Am still awaiting an official response about the lifespan of the original "Sign in with LinkedIn product" and its lifespan on live apps etc.

### CODE REVIEW

**Comment by kevinchalet** [comment]
@solrevdev did you have a chance to make any progress? 😃

**Comment by solrevdev** [comment]
> @solrevdev did you have a chance to make any progress? 😃

@kevinchalet I haven't made progress yet, but upgrading a project from V1 to V2 API is now on my official todo list at work. However, there are priorities ahead of it. If someone else wants to jump in, go ahead.

I'll keep everyone posted when I start.

Just a heads up: LinkedIn isn't retiring the original "Sign in with LinkedIn" product soon, so upgrading to V2 isn't mandatory. But I'm proceeding with the V2 upgrade as we don't plan to support both versions, and there's always the chance LinkedIn could retire V1 later.

**Comment by AaronSadlerUK** [comment]
Hi @solrevdev,

Did you manage to make any head-way with this?

**Comment by solrevdev** [comment]
> Hi @solrevdev,
> 
> Did you manage to make any head-way with this?

Hi @AaronSadlerUK,

No progress yet, tied up with an urgent upgrade due to an upcoming December Royal Mail API shutdown and another project that's more urgent for work. Unlikely to tackle this before Christmas, but I'll try if things ease up. Open to others taking over the PR, or I can close it to clear the way. Will pick it up asap otherwise.

Cheers,
John

**Comment by kevinchalet** [comment]
Looks like this PR went stale, closing.
For those who need to integrate with LinkedIn's OIDC API, the LinkedIn OpenIddict web provider is the recommended option.

**Pull request closed without merging**
