### PR TITLE
Call to Coinbase user profile should be a GET request

### PR DESCRIPTION
**Pull request by levimatheri**

### CODE REVIEW

**Comment by levimatheri** [comment]
Not sure why this failed only on macos?

**Comment by martincostello** [comment]
These changes imply that the original PR was never actually tested against the real service.

Please check the change locally against the actual Coinbase API and verify everything works correctly.

Once you've confirmed that I'll merge this PR and do a new release to NuGet.org.

**Comment by levimatheri** [comment]
@martincostello I've verified everything works correctly now. I tested it on the MvcClient project on this repo as well, works correctly.

**Review by martincostello — APPROVED** [review]

**Comment by martincostello** [comment]
@levimatheri Thanks - if you could validate with the [`5.0.6-preview.21304.48`](https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.Coinbase/5.0.6-preview.21304.48) version from our MyGet feed, then if all is OK I can push up a `5.0.6` release with the fix either later today or tomorrow.

**Comment by levimatheri** [comment]
@martincostello Verified against the MyGet feed version 5.0.6-preview.21304.48. Works correctly. Thank you!

**Comment by martincostello** [comment]
This fix has now been published to [NuGet.org](https://www.nuget.org/packages/AspNet.Security.OAuth.Coinbase/5.0.6).

**Pull request merged**
