### PR TITLE
Add Twitter provider

### PR DESCRIPTION
**Pull request by martincostello**
Add an OAuth 2.0 Twitter provider.

### CODE REVIEW

**Comment by kevinchalet** [comment]
There's already an OAuth 1.0 provider in ASP.NET Core, is there a particular reason to have an OAuth 2.0 provider here? Is there a migration plan that will obsolete OAuth 1.0 at some point?

**Comment by martincostello** [comment]
Check out https://github.com/dotnet/aspnetcore/issues/39664.

**Review by Tratcher — APPROVED** [review]
LGTM

**Comment by martincostello** [comment]
@kevinchalet Thoughts on this? https://github.com/dotnet/aspnetcore/issues/39664#issuecomment-1018800346

Assuming you're happy aspnet-core will keep shipping the OAuth 1.0 provider until whenever, and we'll be the OAuth 2.0 version and sort of "pick up the baton" over time as the Twitter API evolves.

**Comment by kevinchalet** [comment]
> Assuming you're happy aspnet-core will keep shipping the OAuth 1.0 provider until whenever, and we'll be the OAuth 2.0 version and sort of "pick up the baton" over time as the Twitter API evolves.

No objection.

@Tratcher in return, I'd be interested in seeing more contributions from the ASP.NET team: with roughly ~80 packages, this repository is an absolute beast and @martincostello already dedicates a lot of time to it (PR reviews, code and infrastructure maintenance, not to mention the tweaks needed to react to changes introduced in ASP.NET Core itself).

I suspect you - and Hao who's also familiar with the authentication stack - already have a busy schedule and to be 100% clear, I'm not suggesting you guys should do that in your free time, but that would be great if your respective PMs could take that into account to let you contribute to aspnet-contrib from time to time (e.g by triaging issues, reviewing/testing the submitted providers or by keeping the infra/Arcade up-to-date).

**Pull request merged**
