### PR TITLE
Support Vkontakte `email` from access_token

### PR DESCRIPTION
**Pull request by Ranmoro**
to add an opportunity requires add `email` to `scope`

### CODE REVIEW

**Comment by mokeev1995** [comment]
@PinpointTownes can you accept this pr?

**Review by mokeev1995 — APPROVED** [review]
lgtm

**Comment by agoretsky** [comment]
@PinpointTownes Happy New Year To You! Could you please merge this PR?

**Comment by kevinchalet** [comment]
@agoretsky yep, it's on my todo list. It will be part of the next release.

**Comment by kevinchalet** [comment]
This PR was merged into the `release` branch (1.0 providers) and ported to the `dev` branch (2.0): https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/ce9cb278982d27cb251b071418e84fa0718e8d1c

Thanks for your contribution!

**Pull request closed without merging**
