### PR TITLE
Add a Foursquare provider

### PR DESCRIPTION
**Pull request by abhinavnigam**
Change FourSquare to Foursquare - classname, namespace, filename and
project

### CODE REVIEW

**Comment by PinpointTownes** [comment]
Don't open a new PR each time you make a change: it creates unnecessary noise and it's really hard for us to determine what's the one you want us to merge.

Since it's the most recent, I guess it's this one?

**Comment by abhinavnigam** [comment]
As I had rename files, project etc. These causes failure while merging. I am not able to merge the changes. 
Then I delete the existing fork, created new one and committed changes and open new Pull request.
I am using Github for first time and not much aware of it. Just learning.

**Comment by SH2015** [comment]
@abhinavnigam : I am having the same problem that you have in failing AppVeyor and Travis CI  checks , can you elaborate what was the fix that make it pass these checks  ? was it just the renaming problem ?

**Comment by abhinavnigam** [comment]
In my case, it is failing during merging to previous commit done not in AppVeyor and Travis CI checks. 
For that I had deleted the form and exiting local copy of code(after taking backup of changes). Create new fork. Clone it locally. Put my changes an vomit. As this is 1st commit to fork no mergin error occurs. And sen the PR.

**Comment by SH2015** [comment]
Thank you ,I found I was using newer version of some .net components that caused build errors .

**Comment by PinpointTownes** [comment]
Rebased and merged: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/f52afe385f1d672e9c443f420971359b8e36f0ed

@abhinavnigam thanks for your contribution! :+1:

**Pull request closed without merging**
