### PR TITLE
Migrate some providers to ASP.NET Core 2.0 Vol.3

### PR DESCRIPTION
**Pull request by kinosang**
* [x] Instagram
* [x] SoundCloud
* [x] Untappd
* [x] VisualStudio
* [x] Yammer

### CODE REVIEW

**Comment by kinosang** [comment]
@PinpointTownes ping

**Comment by kinosang** [comment]
@PinpointTownes Let's make it

**Comment by kevinchalet** [comment]
@kinosang I'll take some time to merge the remaining providers today 🌮

**Comment by kevinchalet** [comment]
Merged, thanks again! :+1: :clap: 

Just last one favor if you don't mind: could you please send a PR to add your name to the .csproj files of the providers you've migrated to 2.0? That would be awesome.

**Comment by kinosang** [comment]
@PinpointTownes 😄 Just a minute. I'll add my name to those project files.

**Comment by kinosang** [comment]
@PinpointTownes Should the name sort by alphabet or append my name after other contributors?

**Comment by kevinchalet** [comment]
Not sure it makes a different for NuGet. For simplicity, I'd go with the second option :smile:

**Pull request closed without merging**
