### PR TITLE
Added a patreon provider.

### PR DESCRIPTION
**Pull request by Chapelin**
Hi,

My first PR ever, so I might have made mistakes.
Here is a Patreon provider, the sample is up-to-date with a working client Id/secret.

### CODE REVIEW

**Comment by Chapelin** [comment]
It seems Travis fail to get a specific tool, the URL doesn't seems to be valid.
It's not linked to my code.
I don't know how to start a new build, can somebody relaunch it please?

**Comment by kevinchalet** [comment]
Salut Antoine.
Thanks for your PR :+1:

> It seems Travis fail to get a specific tool, the URL doesn't seems to be valid.

The Linux CI is indeed currently broken (I need to fix the .travis.yml file to use a more recent KoreBuild/dotnet version). I'll take care of that this weekend and merge your PR (and the other ones :sweat_smile:)

**Comment by Chapelin** [comment]
Ok, thank you for the feedback !

**Comment by kevinchalet** [comment]
I finally merged your PR: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/c8ae943ac333c9070076f0e3f69300145ea78ebc.

Thanks for your contribution and sorry for the delay.

**Pull request closed without merging**
