### PR TITLE
Add Weixin Provider

### PR DESCRIPTION
**Pull request by zhengchun**
#138 
Test successful

### CODE REVIEW

**Comment by PinpointTownes** [comment]
Thanks for your contribution :+1: 

I'll take a look and merge it when I have a minute.

**Comment by PinpointTownes** [comment]
Sorry for not getting back to you sooner. Reviewing and merging all the PRs of this repo is on my todo list, but I'm currently overbooked with my professional activities. I'll try to dedicate an hour or two next week.

Thanks.

**Comment by zhengchun** [comment]
Thanks @PinpointTownes , :+1:

**Comment by PinpointTownes** [comment]
Merged, thanks for your contribution!

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/bd7adc3570a6c275c1cf12790e21a4f359244409

**Pull request closed without merging**
