### PR TITLE
Add integration tests

### PR DESCRIPTION
**Pull request by martincostello**
This PR builds on top of #280 to add integration tests for the auth providers.

For now there are only 4 implemented, but assuming the general approach is approved, I'll cherry-pick the commit over to the 3.0 branch and add a test for each of the providers to validate the 3.0 work.

Easiest to review by just looking at the diff for [`24f5483..2d2b1a0`](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/282/files/24f548328ccd81a15a5881bec4b8ced59ed60d88..2d2b1a020f4e8b3e5da0b60bfb4ac0e0fd8d1f33).

### CODE REVIEW

**Comment by martincostello** [comment]
I've not included them in this PR to keep the size manageable, but there are now tests for all providers in [this branch](https://github.com/martincostello/AspNet.Security.OAuth.Providers/tree/Moar-Tests/test/AspNet.Security.OAuth.Providers.Tests) which [all pass](https://travis-ci.com/martincostello/AspNet.Security.OAuth.Providers/jobs/185497909#L435), and all the fixes for bugs that the tests found have been cherry-picked back to the branch for #280.

**Comment by martincostello** [comment]
@PinpointTownes Would you be able to offer some feedback on this PR soon please so I could incorporate it into #280?

**Comment by PsiStorm69** [comment]
Good day, Guten Tag!

I am currently traveling until end of April and will respond whenever possible.

Ich bin zur Zeit bis Ende April unterwegs und werde, wann immer möglich, antworten.

Thank you, Danke.

**Comment by kevinchalet** [comment]
@martincostello I'll try this weekend, but no promise.

The good news is that @poke recently accepted to be an aspnet-contrib maintainer and now has write access to this repository so he'll certainly be able to give some feedback (he contributed to the generic OAuth 2.0 handler so it's an area he knows well).

**Comment by kevinchalet** [comment]
Oh and as usual, thanks for your PR 😄

**Comment by martincostello** [comment]
No problem! 😃 

I just wanted to try and keep up the momentum on the 3.0 support 👍

**Comment by poke** [comment]
I'll make sure to take a closer look at this this weekend! We certainly should be ready when 3.0 releases, so catching this momentum early is a very good idea! 😊

**Comment by martincostello** [comment]
@poke Would you be able to take a 👀 at this in the next week?

**Comment by martincostello** [comment]
Replaced by #292.

**Pull request closed without merging**
