### PR TITLE
Add a new README.md file

### PR DESCRIPTION
**Pull request by PinpointTownes**
You can see the final result here: https://github.com/PinpointTownes/AspNet.Security.OAuth.Providers/tree/readme

Feel free to tell me if I missed something :smile: 

/cc @jerriep

### CODE REVIEW

**Comment by jerriep** [comment]
:+1: Why is CI failing though...?

**Comment by PinpointTownes** [comment]
@jerriep because of a (totally unrelated) bug in dnx, that makes build fail on Mono. 
I hope it will be fixed soon.

**Comment by PinpointTownes** [comment]
Merged, thanks for the review :bow:

**Comment by PinpointTownes** [comment]
@jerriep FYI, switching to Mono 4.0 alpha - as suggested by @akoeplinger - fixed the recent issue we had with Mono 4.0: https://travis-ci.org/aspnet-contrib/AspNet.Security.OAuth.Providers/builds/64472532 :gift_heart: 

@akoeplinger thanks the tip, sir! :smile:

**Comment by jerriep** [comment]
:+1: 

Sorry man, I have not had any chance to look at any of this... :)

**Pull request merged**
