### PR TITLE
Added a new Mail.ru authentication provider for ASP.NET Core 2.0.

### PR DESCRIPTION
**Pull request by Ranmoro**
Mail.Ru Group, ООО (commonly referred to as Mail.Ru) is a Russian Internet company. It was started in 1998 as an e-mail service and went on to become a major corporate figure in the Russian-speaking segment of the Internet. As of 2013 according to comScore, websites owned by Mail.ru collectively had the largest audience in Russia and captured the most screen time.

### CODE REVIEW

**Comment by mokeev1995** [comment]
@PinpointTownes what about this pr?

**Comment by martincostello** [comment]
Thank you for your PR @Ranmoro - is this something you still wish to pursue?

**Comment by martincostello** [comment]
Closing due to inactivity and merge conflicts - please re-open and rebase if you would like to pursue adding a provider for Mail.ru in a future release.

**Comment by martincostello** [comment]
Superseded by #306.

**Pull request closed without merging**
