### PR TITLE
Use Arcade for build

### PR DESCRIPTION
**Pull request by martincostello**
Switch to Arcade to build the project.

Addresses #321.

### CODE REVIEW

**Comment by martincostello** [comment]
_Almost_ done.

The only thing missing is that the test results [aren't reported](https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-oauth-providers/builds/26768704/tests) in AppVeyor.

Any ideas @PinpointTownes? I can [see them](https://ci.appveyor.com/project/openiddict/openiddict-core/builds/26757595/tests) in openiddict-core. 🤔

**Comment by kevinchalet** [comment]
> Any ideas @PinpointTownes?

Honestly no. It's weird: they are correctly executed but not reported 😕 

(note: you shouldn't merge it until we solve the versioning issue, otherwise it will be a PITA for nightly builds 😄)

**Comment by martincostello** [comment]
Yeah, I'm just having a dig around in the code and docs now to see if I can work it out.

We _might_ have to add some custom MSBuild overrides somewhere to take the AppVeyor properties and turn them into AzDO ones for Arcade to pick up.

**Comment by martincostello** [comment]
So from looking at this:

https://github.com/dotnet/arcade/blob/331447d81b1968bed7161c4a6a8d70e4990327e1/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.BeforeCommonTargets.targets#L18-L25

and the [AppVeyor](https://www.appveyor.com/docs/environment-variables/) docs, I think we can "fix" it by adding this to `Directory.Build.props`:

```xml
<OfficialBuild Condition=" '$(APPVEYOR)' == 'True' AND '$(APPVEYOR_PULL_REQUEST_NUMBER)' == '' ">true</OfficialBuild>
```

**Comment by kevinchalet** [comment]
We can, but it has a downside: in this case, it generates an official build number based on the current date with a fixed ".1" revision, so if we merge more than 1 commit a day, it will end up overwriting existing packages.

We could provide an `OfficialBuildId`, but the format doesn't allow revisions that have more than 2 digits. Since AppVeyor build numbers are not reset every day, it's super limiting 😢

**Comment by martincostello** [comment]
Hmm. I'll have a further think about the revision part...

**Comment by martincostello** [comment]
OK, I'm not proud of this, but it works*...

*as long as you don't publish to MyGet more than once per quarter of the hour.

If we have to rollover every 24 hours, and we can't have more than 2 digits, what about an auto-incrementing build number that's based on which quarter-hour of the day it is right now?

There's 24 hours in a day, so there's 96 quarter hours a day.

A build between `00:00:00` and `00:14:59` would be revision `1`.
A build between `23:45:00` and `23:59:59` would be revision `97`.

If I run this command on my laptop at 20:29, I get this:

```cmd
.\build.cmd -pack /p:APPVEYOR=True

<...lots of build output...>

Successfully created package 'AspNet.Security.OAuth.MailRu.3.0.0-dev.19417.82.symbols.nupkg'.
```

Code to add to `Directory.Build.props` below:

```xml
<!--
  Arcade only allows the revision to contain up to two characters, and AppVeyor does not roll-over
  build numbers every day like Azure DevOps does. To balance these two requirements, set the official
  build ID to be the same format as the built-in default from Arcade, except with the revision number
  being the number of the quarter hour of the current time of day (24 * 4 = 96, which is less than 100).
  So a build between 00:00 and 00:14 would have a revision of 1, and a build between 23:45 and 23:59:59
  would have a revision of 97.
-->
<PropertyGroup Condition=" '$(APPVEYOR)' == 'True' AND '$(APPVEYOR_PULL_REQUEST_NUMBER)' == '' ">
  <_Hours>$([MSBuild]::Multiply($([System.DateTime]::Now.ToString(HH)), 4))</_Hours>
  <_QuarterHours>$([MSBuild]::Divide($([System.DateTime]::Now.ToString(mm)), 15))</_QuarterHours>
  <_QuarterHours>$([System.Math]::Floor($(_QuarterHours)))</_QuarterHours>
  <_AppVeyorBuildRevision>$([MSBuild]::Add($(_Hours), $(_QuarterHours)))</_AppVeyorBuildRevision>
  <_AppVeyorBuildRevision>$([MSBuild]::Add($(_AppVeyorBuildRevision), 1))</_AppVeyorBuildRevision>
  <OfficialBuild>true</OfficialBuild>
  <OfficialBuildId Condition=" '$(OfficialBuild)' == 'true' ">$([System.DateTime]::Now.ToString(yyyyMMdd)).$(_AppVeyorBuildRevision)</OfficialBuildId>
</PropertyGroup>
```

**Comment by kevinchalet** [comment]
Clever (and certainly better than nothing 😅)

That said, I'll ping the Arcade folks to see what they think about that, just to make sure we're not missing something obvious.

**Comment by martincostello** [comment]
Sure, this is definitely a hack!

**Comment by martincostello** [comment]
Thoughts on merging this as-is and opening a new PR if we find a better solution via https://github.com/dotnet/arcade/issues/3706?

**Comment by martincostello** [comment]
I'm going to merge this to the 3.0.0 branch with the current "1/4 hours in a day" versioning approach so I can make a start on the updates for preview 9 with minimal fuss.

**Pull request merged**
