### PR TITLE
Improvement for LINE provider

### PR DESCRIPTION
**Pull request by linmasaki**
Recently, I discovered that if users didn't log in to the LINE first at the browser, the login page would not show for users.

Set the prompt value to an empty string can resolve this issue.

### CODE REVIEW

**Comment by martincostello** [comment]
This seems a reasonable fix based on the description. As we can't validate this behaviour with our CI tests, can you confirm that running this change against the real Line service locally results in the expected behaviours for the two scenarios you've identified?

**Comment by linmasaki** [comment]
Yes, I tested it on real LINE service and confirmed this alteration didn't break the old application.

**Comment by martincostello** [comment]
Thanks for the fix - this will go out with the 5.0.9 release. Until that releases (after #579 is merged), you can consume the fix from our MyGet feed.

**Comment by martincostello** [comment]
This change is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.Line/5.0.9

**Comment by linmasaki** [comment]
> This change is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.Line/5.0.9

Thanks!

**Pull request merged**
