### PR TITLE
Added a new Dribbble authentication provider for ASP.NET Core 2.0.

### PR DESCRIPTION
**Pull request by haydenhancock**
Added a new authentication provider for Dribbble. #189

### CODE REVIEW

**Comment by kevinchalet** [comment]
@haydenhancock thanks for your PR. Could you please move the 1.0 -> 2.0 migration commits to a separate PR?

**Comment by haydenhancock** [comment]
@PinpointTownes What do you mean? Do you mean separate the new authentication provider, Dribbble from MailChimp and Gitter?

**Comment by kevinchalet** [comment]
@haydenhancock yes, but feel free to keep MailChimp and Gitter in the same PR.

The reason is simple: I don't want to add new providers to the `experimental` branch before we're done with the existing providers. If we want to merge your migration commits, it's easier if they are in a separate PR.

**Comment by haydenhancock** [comment]
@PinpointTownes Makes perfect sense. I apologize for screwing that up!

**Comment by haydenhancock** [comment]
@PinpointTownes What is actually the best way to achieve this? Sorry, I am new to Git.

**Comment by kinosang** [comment]
@haydenhancock you can reset HEAD to 2b4860f (maybe with a GUI tool), create a new branch from 356d626 and commit your migrated providers on the new branch, then make pull request from your new branch to  aspnet-contrib:experimental.

or you can reset HEAD to 356d626 and commit those providers on haydenhancock:experimental and create new branch (and pull request) for Dribbble provider.

**Comment by haydenhancock** [comment]
@kinosang I reset to 2b4860f and created a new branch from 356d626 but it's asking to commit or undo changes before I switch branches. I selected undo and now all my local changes are gone.

**Comment by kinosang** [comment]
@haydenhancock oops, I'm sorry for that. maybe you can pull or clone your online repo to recover your changes.

I use SourceTree and it can keep my changes when I switch branches.

I'm not expert on Git, so I usually make a backup of my changes, create new branch (and switch to it), then restore my changes from backup if changes lost.

**Comment by haydenhancock** [comment]
@kinosang It's not your fault! I am using Visual Studio 2017 with the GitHub extension. This is definitely a learning experience for me. I am about to make another pull request from a new branch. Does this pull request subsequently get removed?

**Comment by kinosang** [comment]
@haydenhancock just close this pull request by clicking the `close` button on the bottom of this page if you  want to "get it removed".

**Comment by martincostello** [comment]
Closing due to age and the number of conflicts.

Please re-open a new PR if you would like to pursue adding a provider for Dribble further. Thanks!

**Pull request closed without merging**
