### PR TITLE
Strava authentication

### PR DESCRIPTION
**Pull request by Moza805**
Updated the Strava authentication to work on ASP.NET Core 2.0.

Usage:
Update `ConfigureServices` on `Startup`.

```csharp
services.AddAuthentication(
{
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
})

.AddCookie(options =>
{
    options.LoginPath = "/login";
    options.LogoutPath = "/signout";
})

.AddStrava(options =>
{
    options.ClientId = "<your-id>";
    options.ClientSecret = "<your-secret";
});
```

### CODE REVIEW

**Comment by kevinchalet** [comment]
Thanks for your PR. I took a brief look and I see many inconsistencies with the other providers (e.g we don't want to add the claims using the events model as the default logic would be lost if the users provided their own delegates).

Please fix the inconsistencies (including styling differences) and squash your PR.

**Comment by Moza805** [comment]
Thanks for feedback, I'll pick it up this evening after work.

**Comment by Moza805** [comment]
Please review again.

- Moved claims logic into the `StravaAuthenticationHandler` as requested. 
- Scope is now handled in `StravaAuthenticationOptions` as per other OAuth providers.
- Removed `StravaAuthenticationHelper` as per other OAuth providers.
- Re-ordered a summary parameter comment on `StravaAuthenticationDefaults`

Let me know if there's anything else, looking forward to your feedback.

**Comment by kevinchalet** [comment]
Merged, thanks for your PR! https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/50eb197a1396ee81321a539ba61602aa3434c889

**Pull request closed without merging**
