### PR TITLE
Add JetBrains Hub provider.

### PR DESCRIPTION
**Pull request by StummeJ**

### CODE REVIEW

**Comment by StummeJ** [comment]
In response to Issue #109

**Comment by StummeJ** [comment]
I dont have a hub server to test this on...

**Comment by PinpointTownes** [comment]
> I dont have a hub server to test this on...

This is a bit problematic, as I don't use JetBrains either. Do you know someone who could help test it?

**Comment by StummeJ** [comment]
@macgyver76 was the original requester of this feature in issue #109.  possibly him?

**Comment by PinpointTownes** [comment]
@macgyver76 any chance you could give us a hand? :smile:

**Comment by macgyver76** [comment]
@PinpointTownes - you can install hub server on your local machine. Sorry, I haven't got time for checking that at the moment.

**Pull request closed without merging**
