### PR TITLE
Add Amazon provider

### LINKED ISSUE #156: Add an Amazon provider
_Originally raised as aspnet/Security#1204_

I recently implemented support for Amazon login in a project by building on top of the OAuth NuGet package.

Would there be any interest in accepting a PR to make an implementation of that available in this repo like there is for Facebook, Twitter etc.? I can't see an existing one, or one in progress in the issues or PR list.

I thought I'd ask before starting the PR, rather than just submit it out of the blue.

### PR DESCRIPTION
**Pull request by martincostello**
This PR adds a provider to use for [Login with Amazon](http://login.amazon.com/website).

Resolves #156.

### CODE REVIEW

**Comment by martincostello** [comment]
@PinpointTownes What kind of timescale is there for this being reviewed, merged and published to NuGet?

**Comment by PinpointTownes** [comment]
> @PinpointTownes What kind of timescale is there for this being reviewed, merged and published to NuGet?

Sorry for not getting back to you sooner. Reviewing and merging all the PRs of this repo is on my todo list, but I'm currently overbooked with my professional activities. I'll try to dedicate an hour or two next week.

Thanks.

**Comment by martincostello** [comment]
👍

**Comment by PinpointTownes** [comment]
Merged, thanks for your contribution! :clap: 

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/12cc086ea470d9d9689aef823475c5dd886a8049

**Pull request closed without merging**
