### PR TITLE
Add weixin webpage provider

### PR DESCRIPTION
**Pull request by huww98**

### CODE REVIEW

**Comment by huww98** [comment]
Related #168

**Comment by kevinchalet** [comment]
Thanks for your PR, @huww98.

Unfortunately, the fact it relies on such an ugly hack to work around Weixin's state limitation makes it way too inconsistent with all the other providers, so I'm not sure it's a good candidate for this repository.

Have you tried to contact Weixin to remove their stupid limit?

**Comment by huww98** [comment]
@PinpointTownes No, I have not. I have never tried to contact such a big company like Tencent (the owner of Weixin). I don't know whether I can get a response from them.

Weixin have 600 million users. In China, almost everyone is using Weixin!

 Anyway, I will try to contact them.

Update: I have send an e-mail to them and waiting for the response.

**Comment by kevinchalet** [comment]
@huww98 did you hear back from Tencent?

> Weixin have 600 million users. In China, almost everyone is using Weixin!

Any chance you could remind me when the existing Weixin provider couldn't be used?

**Comment by huww98** [comment]
No, I did not hear back from them.

There‘s not much relevance between these two providers. The existing Weixin provider is very different from this one. The existing one is for [Weixin Open Platform](https://open.weixin.qq.com/), but this one is for [Weixin Public Platform](https://mp.weixin.qq.com/). The existing one is for APPs other than Weixin to get user's info, this one is for websites shown in Weixin APP to get user's info.

**Comment by martincostello** [comment]
Thank you for your PR @huww98 - is this something you still wish to pursue? Has this been superseded by #266?

**Comment by martincostello** [comment]
Closing due to inactivity and merge conflicts - please re-open and rebase if you would like to pursue this further if the capabilities of the current Weixin provider are insufficient.

**Pull request closed without merging**
